path:
  result: "results/table5/SylReg-Distill.csv"

dataset:
  HF_HOME: "~/.cache/huggingface"
  name: "ryota-komatsu/s5-hubert"  # https://huggingface.co/datasets
  libritts_dir: "data/LibriTTS_R" # ${root}/train-clean-100, train-clean-360, ...
  hfc_dir: "data/hi-fi-captain/en-US"

  ext_audio: ".wav"

  eval_dir: "data/LibriSpeech/test-clean"

flow_matching:
  training_args:
    output_dir: "models/flow_matching"
    per_device_train_batch_size: 200
    gradient_accumulation_steps: 1
    learning_rate: 0.001
    weight_decay: 0.01
    adam_beta1: 0.9
    adam_beta2: 0.95
    max_grad_norm: 0.1
    max_steps: 200000
    lr_scheduler_type: "constant_with_warmup"
    warmup_steps: 1000
    save_steps: 10000
    save_total_limit: null
    bf16: true
    eval_steps: 10000
    dataloader_num_workers: 16
    remove_unused_columns: false
    optim: "adamw_torch_fused"
    report_to: "tensorboard"
    ddp_find_unused_parameters: false
    resume_from_checkpoint: null

  finetuning_args:
    output_dir: "models/flow_matching"
    per_device_train_batch_size: 500
    gradient_accumulation_steps: 14
    learning_rate: 0.0001
    weight_decay: 0.01
    adam_beta1: 0.9
    adam_beta2: 0.95
    max_grad_norm: 0.1
    max_steps: 50
    save_steps: 10
    bf16: true
    remove_unused_columns: false
    optim: "adamw_torch_fused"
    report_to: "tensorboard"
    ddp_find_unused_parameters: false
    resume_from_checkpoint: "models/flow_matching/checkpoint-200000"

  model_args:
    vocab_size: 8192
    num_mel_bins: 80
    embedding_dim: 768
    hidden_size: 512
    num_hidden_layers: 4
    num_attention_heads: 2
    intermediate_size: 1024
    attention_dropout: 0.0
    cfg_dropout: 0.2
    mean: -5.8843  # mean of log mel-spectrogram
    std: 2.2615  # std of log mel-spectrogram
    rope_theta: 10000.0
    dt: 0.1
    cfg_strength: 0.7  # classifier-free guidance (https://arxiv.org/abs/2207.12598)

vocoder:
  model_name_or_path: "ryota-komatsu/bigvgan"
  batch_size: 20
  segment_size: 16080
  num_workers: 20
  training_epochs: 57  # 1M steps
  total_steps: 1000000

  num_gpus: 1
  learning_rate: 0.0001
  adam_b1: 0.8
  adam_b2: 0.99
  lr_decay: 0.9999996
  seed: 1234

  model_in_dim: 80
  upsample_rates: [5, 4, 4, 2, 2]
  upsample_kernel_sizes: [10, 9, 8, 4, 4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]

  mpd_reshapes: [2, 3, 5, 7, 11]
  use_spectral_norm: false
  discriminator_channel_mult: 1
  
  use_multiscale_melloss: true
  lambda_melloss: 15

  clip_grad_norm: 100

  n_fft: 400
  hop_size: 320

  dist_config:
    dist_backend: "nccl"
    dist_url: "tcp://localhost:54321"
    world_size: 1

  stdout_interval: 1000
  summary_interval: 1000
  checkpoint_interval: 10000
  validation_interval: 10000

speech2unit:
  model_name_or_path: "ryota-komatsu/SylReg-Distill"

unit2speech:
  model_name_or_path: "ryota-komatsu/SylReg-Decoder"

asr:
  model_name_or_path: "openai/whisper-large-v3"