dataset:
  name: "ryota-komatsu/SylReg"

  HF_HOME: "~/.cache/huggingface"
  APP_DIR: "data/zr-data"
  tSC_DIR: "data/tSC"
  sSC_DIR: "data/sSC"
  eval_dir: "data/LibriSpeech/test-clean"

model_args:
  name: "Qwen/Qwen2.5-7B"
  defrost_steps: 5000

training_args:
  output_dir: "models/speechlm"
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 16
  learning_rate: 0.0003
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.95
  max_grad_norm: 0.5
  max_steps: 15000
  lr_scheduler_type: "warmup_stable_decay"
  lr_scheduler_kwargs: {"num_decay_steps": 5000, "min_lr_ratio": 0.1, "decay_type": "linear"}
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  save_total_limit: null
  bf16: true
  use_liger_kernel: true
  eval_steps: 5000
  dataloader_num_workers: 16
  remove_unused_columns: false
  deepspeed: "configs/speechlm/ds_zero2_bf16.json"
  optim: "adamw_torch_fused"
  report_to: "tensorboard"
  ddp_find_unused_parameters: false
  resume_from_checkpoint: null
  # assistant_only_loss: true
  # loss_type: "dft"
  # eos_token: "<|im_end|>"

speech2unit:
  model_name_or_path: "ryota-komatsu/SylReg-Distill"
  vocab_size: 8192

unit2speech:
  model_name_or_path: "ryota-komatsu/SylReg-Decoder"

asr:
  model_name_or_path: "openai/whisper-large-v3"

textlm:
  model_name_or_path: "allenai/OLMo-2-0425-1B"