common:
  disable_tqdm: true # set true when using nohup
  seed: 0

path:
  checkpoint: "facebook/hubert-base-ls960"
  quantizer1: "models/hubert/quantizer1.joblib"
  quantizer2: "models/hubert/quantizer2.npy"
  segment_dir: "segments/hubert"
  result: "results/hubert.json"

dataset:
  root: "data" # ${root}/LibriSpeech/train-clean-100, train-clean-360, ...
  download: false
  max_sample_size: 80160 # 5.01 [s]
  train_file: "src/sdhubert/files/librispeech_train_10Ksubset.txt"
  dev_file: "src/sdhubert/files/librispeech_val.txt"
  test_file: "src/sdhubert/files/librispeech_test.txt"
  dev_alignment: "src/sdhubert/files/librispeech_syllable_val.json"
  test_alignment: "src/sdhubert/files/librispeech_syllable_test.json"

dataloader:
  batch_size: 72 # work with single 24GB VRAM GPU
  num_workers: 30

model:
  model_type: "hubert"
  segmentation_layer: 8

n_clusters:
  step1: 16384
  step2: 4096